### ISSUE TITLE
Optionally display a more detailed version of the help text for a question.

### ISSUE THREAD

**Issue by chsinn** [rdmorganiser/rdmo#595]
### Rationale / Begründung

Long help texts are tiring to read and can be off-putting. A more detailed version of the help text could only be displayed if the user clicks on "Read more". 

### Minimal functionality

Clicking on "read more" enlarges the text box and more paragraphs appear without reloading the web page.
![issues_read_more](https://user-images.githubusercontent.com/113421464/224029207-f357193e-c9b7-4120-8783-8a5e77374574.png)

### References / Verweise

* rdmo v1.92

**Comment by MyPyDavid** [comment]
There is currently a help text in the [DFG Checklist](https://github.com/rdmorganiser/rdmo-catalog/blob/6c0798b908d8192fac8bdcfcadf51137f2f1f1f9/rdmorganiser/questions/DFG-Checkliste.xml#L105) catalog that uses the html `<details>` element. It also has a `style="color:blue; cursor:pointer;"` hard coded in it which is not so desirable when someone wants to have another color for example.
The `<details>` and `<summary>` may behave different depending on browsers (https://www.scottohara.me/blog/2022/09/12/details-summary.html) but it works at html in the helptext.
Could this also be an option and include the style in the rdmo `.scss` files?
```scss
/* in rdmo/core/static/core/css/base.scss */
summary {
    color: $details-summary-color;
    cursor: $details-summary-cursor;
}
```
```scss
/* rdmo/core/static/core/css/variables.scss */
/* details summary */
$details-summary-color: #101F70;
$details-summary-cursor: pointer;
```

**Comment by jochenklar** [comment]
I would not add additional colors, but use those which are already available in variables.scss, we could add something like `$summary-color: $link-color;` or something. I don't see why details should have a pointer cursor, but maybe I am missing something.

**Comment by MyPyDavid** [comment]
ok, good idea to use the `$link-color` for that. The pointer cursor is there to make it look like a clickable element when hovering over with the mouse I think, otherwise it looks like a normal text..

**Comment by jochenklar** [comment]
I had a look at `display/summary` again and I would rather go with:

```css
details {
    margin-bottom: 10px;
}

summary {
    display: list-item;
    cursor: pointer;
    margin-bottom: 5px;
}
```
(not changing the color).

![image](https://github.com/rdmorganiser/rdmo/assets/1799675/f2f9275f-7379-4116-8d65-e03e54571508)

@MyPyDavid ok?
