### ISSUE TITLE
Add npm section to dependabot configuration

### ISSUE THREAD

**Issue by afuetterer** [rdmorganiser/rdmo#678]
#649 introduces NPM dependencies in a package.json.

Should dependabot look at those as well? Can be achieved with:

```yaml
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
```
